[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.all-in-one"

[deploy]
startCommand = "/startup.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "80"
