[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.all-in-one"

[deploy]
startCommand = "/startup.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
port = 80
